create table players
(
    id           bigserial primary key,
    first_name   varchar(255) not null,
    last_name    varchar(255) not null,
    address      text         null,
    phone_number varchar(20)  null,
    email        varchar(50)  null,
    rank         int          not null,
    club_id      int references club (id) on delete cascade
);

insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Brooke', 'O''Luby', null, '1331377350', 'boluby0@desdev.cn', 2645, 10);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Clarissa', 'Maddigan', null, '9617012091', 'cmaddigan1@thetimes.co.uk', 2938, 31);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Theodora', 'Truluck', '116 Springview Avenue', '4505974019', 'ttruluck2@forbes.com', 1849, 5);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Andy', 'Klainer', null, '3317584204', 'aklainer3@google.com.au', 2568, 4);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Jasen', 'Valens-Smith', null, '4514851177', 'jvalenssmith4@free.fr', 2171, 14);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Myrwyn', 'Warwicker', '366 Porter Terrace', null, 'mwarwicker5@ucla.edu', 2501, 19);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Eadie', 'Rauprich', null, '2709849869', 'erauprich6@foxnews.com', 2926, 29);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Jenica', 'Barney', '2490 Cherokee Road', null, 'jbarney7@sphinn.com', 2093, 22);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Garrik', 'McGuiney', null, '9891147511', 'gmcguiney8@trellian.com', 2465, 20);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Cornell', 'Kainz', '5051 School Drive', '8137877453', 'ckainz9@prweb.com', 2630, 46);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Torey', 'Brocklebank', null, '6127873921', 'tbrocklebanka@google.co.jp', 2992, 15);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Celie', 'Calbreath', null, '9522214644', 'ccalbreathb@indiatimes.com', 2210, 5);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Carlee', 'Dimitru', null, '9012196407', 'cdimitruc@wikipedia.org', 2891, 14);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Hector', 'Klaesson', '8 Forest Run Park', '4082634164', null, 2459, 28);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Fayina', 'Spracklin', null, '9297138996', 'fsprackline@nationalgeographic.com', 2133, 28);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Travis', 'Duckers', null, '1513748074', 'tduckersf@howstuffworks.com', 1885, 35);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Daveta', 'Lambart', '1 New Castle Park', null, 'dlambartg@dot.gov', 2057, 28);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Leighton', 'Slaughter', null, null, null, 2014, 45);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Jud', 'Shubotham', null, '2152587357', 'jshubothami@usnews.com', 2083, 34);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Philippine', 'Ribbens', '1 Graceland Junction', '9902643982', 'pribbensj@cloudflare.com', 2866, 30);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Blakeley', 'Buxcey', null, '3388177592', 'bbuxceyk@mediafire.com', 2421, 13);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Minerva', 'Bengal', '7742 Basil Alley', null, 'mbengall@blogs.com', 1945, 29);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Conrad', 'Bolino', null, '2405275778', 'cbolinom@google.ca', 2970, 10);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Ilaire', 'Meiningen', null, '5365637470', 'imeiningenn@trellian.com', 2658, 29);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Selle', 'Grimble', null, '1843442457', null, 1852, 16);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Anatola', 'Stode', null, null, 'astodep@state.gov', 2927, 42);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Zsa zsa', 'McNiven', null, '6988217009', 'zmcnivenq@odnoklassniki.ru', 2808, 17);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Clarisse', 'Kitt', null, null, 'ckittr@youku.com', 2832, 35);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Quinton', 'Lindroos', null, '1796026325', 'qlindrooss@wisc.edu', 2650, 21);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Fenelia', 'Kneebone', null, null, 'fkneebonet@home.pl', 2061, 11);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Denis', 'Fauguel', null, '3467871714', 'dfauguelu@cbsnews.com', 2016, 40);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Tomasine', 'Edlington', null, '6285197961', 'tedlingtonv@yandex.ru', 2092, 35);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Karrah', 'Stillgoe', null, null, 'kstillgoew@ovh.net', 2704, 21);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Lavinia', 'Anten', '401 Sauthoff Hill', '9303572729', 'lantenx@quantcast.com', 1818, 5);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Dotti', 'Abramov', null, '8445531524', 'dabramovy@free.fr', 2655, 15);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Thorvald', 'Menego', null, null, 'tmenegoz@linkedin.com', 1662, 47);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Dulci', 'Maunder', '08 Moland Place', '5035921647', 'dmaunder10@shop-pro.jp', 1721, 19);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Isacco', 'Cawthery', null, null, 'icawthery11@nbcnews.com', 1733, 50);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Stanislaw', 'Bagnell', null, null, 'sbagnell12@cloudflare.com', 1783, 2);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Carleen', 'Ringrose', null, '5206218757', null, 2083, 24);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Bentley', 'Kinsell', null, '9302816060', 'bkinsell14@umich.edu', 1965, 25);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Adlai', 'Schuelcke', null, '4957694389', 'aschuelcke15@china.com.cn', 1940, 7);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Owen', 'Stallworthy', '624 Lillian Terrace', '5566392181', 'ostallworthy16@sciencedaily.com', 1670, 26);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Farand', 'Gever', '396 Village Court', '6207875622', 'fgever17@printfriendly.com', 2278, 32);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Dina', 'Upex', '02 Menomonie Circle', '5193260183', 'dupex18@elegantthemes.com', 1526, 7);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Hewe', 'Leitch', null, null, 'hleitch19@blogs.com', 2806, 9);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Regen', 'Peetermann', null, '5604456499', 'rpeetermann1a@so-net.ne.jp', 2656, 34);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Doria', 'Petrishchev', null, '5794271251', 'dpetrishchev1b@ezinearticles.com', 2183, 14);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Issy', 'Grevatt', null, '4884337265', 'igrevatt1c@hugedomains.com', 1949, 6);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Matt', 'Willatt', null, '3376730976', 'mwillatt1d@soup.io', 2981, 36);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Em', 'Espinha', null, '1887908793', 'eespinha1e@spiegel.de', 2268, 47);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Halimeda', 'Tayloe', null, '4092452306', 'htayloe1f@xinhuanet.com', 2068, 17);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Tabbie', 'Mouth', '3 Daystar Crossing', '3317802601', null, 2245, 50);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Frasco', 'Birmingham', '14809 Meadow Vale Court', '3441743037', 'fbirmingham1h@umn.edu', 1622, 2);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Betta', 'Sharpe', null, '8014711289', 'bsharpe1i@ftc.gov', 1851, 12);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Kelsey', 'Churm', null, '8212833962', null, 2552, 43);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Channa', 'Lisciandri', null, '7089604992', 'clisciandri1k@sina.com.cn', 2913, 6);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Gus', 'Shankland', null, '5326758207', 'gshankland1l@linkedin.com', 2242, 40);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Henrieta', 'Gurnell', null, null, 'hgurnell1m@nbcnews.com', 2369, 9);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Shelagh', 'Besson', null, '3672324551', 'sbesson1n@reuters.com', 2801, 16);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Bria', 'Crabbe', null, '1805954445', 'bcrabbe1o@smh.com.au', 1574, 41);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Peyton', 'McCue', null, '8329865576', 'pmccue1p@privacy.gov.au', 2727, 31);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Curtis', 'Myott', '448 Aberg Center', '4916200912', 'cmyott1q@freewebs.com', 1613, 20);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Leif', 'Regglar', null, '2876853111', 'lregglar1r@usa.gov', 1675, 29);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Kipp', 'Critten', null, '4216766989', 'kcritten1s@last.fm', 1608, 17);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Sibylla', 'Scalia', '171 Autumn Leaf Alley', '3222928264', 'sscalia1t@desdev.cn', 1707, 38);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Cornall', 'Gallahue', null, null, 'cgallahue1u@npr.org', 1748, 8);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Harcourt', 'Mattersley', null, '1974728033', 'hmattersley1v@time.com', 1911, 38);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Casie', 'Pymm', null, null, 'cpymm1w@forbes.com', 1994, 48);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Griffith', 'Claw', null, '3625614223', 'gclaw1x@nymag.com', 1639, 38);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Roxanne', 'Rathbourne', null, '2845280999', 'rrathbourne1y@ning.com', 2099, 42);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Barrie', 'Cutting', '501 Gerald Road', '2641436378', 'bcutting1z@biblegateway.com', 2344, 41);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Cristi', 'Siddens', null, '5391277953', 'csiddens20@bing.com', 2452, 16);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Nonah', 'Lyston', '59942 Northridge Hill', '4583030922', null, 1941, 9);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Ev', 'Howel', null, '2893285896', 'ehowel22@ox.ac.uk', 2156, 31);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Robena', 'Rustidge', null, '6274772710', 'rrustidge23@craigslist.org', 1871, 18);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Mill', 'Tadgell', '8 Schiller Way', null, 'mtadgell24@behance.net', 2953, 17);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Netta', 'Giffaut', null, '1614073740', 'ngiffaut25@prlog.org', 2257, 26);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Darrel', 'Patrono', null, '4581294450', 'dpatrono26@nifty.com', 2423, 11);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Erasmus', 'Jeste', '41 Arizona Junction', '6781681342', 'ejeste27@stanford.edu', 1854, 33);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Mavis', 'Sachno', null, '3995823452', 'msachno28@cyberchimps.com', 2053, 28);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Thomasa', 'Blind', null, '3571678480', 'tblind29@miitbeian.gov.cn', 1668, 36);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Iver', 'O'' Mahony', '19 Service Way', '4478004887', 'iomahony2a@who.int', 1739, 28);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Danya', 'Ormesher', '59770 Harbort Trail', '2453962955', 'dormesher2b@xing.com', 2049, 13);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Gena', 'Glacken', null, null, 'gglacken2c@state.gov', 1707, 38);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Georgine', 'Mulrenan', null, '2111471532', 'gmulrenan2d@ihg.com', 2202, 7);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Quinlan', 'Tremellan', null, null, 'qtremellan2e@washington.edu', 2602, 26);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Sergei', 'Crookshanks', '62 Doe Crossing Road', null, 'scrookshanks2f@bloomberg.com', 2294, 31);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Katinka', 'Devonside', '033 Bartelt Road', '1122630785', 'kdevonside2g@miibeian.gov.cn', 1985, 8);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('August', 'Dumbarton', null, '8862776455', null, 2930, 39);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Stearn', 'Muat', null, '7479601244', 'smuat2i@google.es', 1865, 33);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Zolly', 'Rumford', '426 Arapahoe Park', '8414524039', 'zrumford2j@mac.com', 2130, 23);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Brandtr', 'Fenne', null, '1882272987', 'bfenne2k@surveymonkey.com', 1943, 8);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Ranna', 'Ghidetti', null, '2616016226', 'rghidetti2l@blogs.com', 2899, 41);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Susann', 'Bear', null, '3803896565', 'sbear2m@oracle.com', 2385, 28);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Lyndsey', 'Hanbidge', null, null, 'lhanbidge2n@un.org', 2625, 22);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Ky', 'Sibthorpe', null, '1171537651', null, 2203, 30);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Denney', 'Hakewell', null, '3511865666', 'dhakewell2p@gizmodo.com', 1855, 25);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Merna', 'Gabbitis', null, '8327380704', 'mgabbitis2q@ustream.tv', 1543, 7);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Carlita', 'Verty', null, '4738484254', 'cverty2r@cocolog-nifty.com', 2050, 4);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Chelsy', 'Yarwood', null, null, 'cyarwood2s@engadget.com', 1681, 45);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Donnie', 'Cordner', null, '2081867290', 'dcordner2t@de.vu', 2882, 9);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Mela', 'Georges', null, null, 'mgeorges2u@apache.org', 2857, 48);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Mirilla', 'Matts', null, '1956242552', 'mmatts2v@blog.com', 1620, 36);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Mortimer', 'Freire', null, '5643131204', 'mfreire2w@bbb.org', 2595, 42);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Maddi', 'Sowle', '9 Kipling Center', '1169807640', 'msowle2x@mlb.com', 2302, 47);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Britteny', 'Halkyard', null, '2657757591', null, 1588, 8);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Norah', 'Kopp', null, '3658317611', 'nkopp2z@cloudflare.com', 2623, 12);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Tessa', 'Molan', null, '6561881874', 'tmolan30@google.pl', 2265, 4);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Frazer', 'Gullen', '84 Village Court', null, 'fgullen31@icq.com', 1813, 25);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Ashlan', 'Dacombe', null, '7612030085', 'adacombe32@yandex.ru', 2250, 28);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Malvin', 'Hugh', null, null, 'mhugh33@cbslocal.com', 2737, 47);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Hamlin', 'Mulhall', null, '1828711751', 'hmulhall34@indiegogo.com', 2470, 37);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Marlyn', 'Threadgold', null, '7345750587', 'mthreadgold35@nydailynews.com', 1598, 29);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Cece', 'Gavaghan', null, '5747546934', 'cgavaghan36@live.com', 2194, 28);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Karl', 'Jon', '6 Washington Center', '6133182602', 'kjon37@digg.com', 2406, 26);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Tory', 'Hancox', '675 Moland Hill', '9656098537', 'thancox38@shop-pro.jp', 2075, 41);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Skipp', 'Duffer', null, '5321337927', 'sduffer39@ifeng.com', 2753, 26);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Lesley', 'Mays', null, '6333218416', 'lmays3a@mediafire.com', 2252, 24);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Robby', 'Ginman', null, null, null, 1863, 27);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Rosalie', 'Toffaloni', null, '8776628490', 'rtoffaloni3c@barnesandnoble.com', 2570, 35);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Omar', 'Ladd', '63 Superior Junction', '1874474511', 'oladd3d@exblog.jp', 2520, 49);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Betteanne', 'Nurse', null, '5753621267', 'bnurse3e@yellowbook.com', 1638, 33);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Heindrick', 'Lincke', null, '5175945725', 'hlincke3f@newyorker.com', 1833, 15);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Beaufort', 'Flippen', null, '3712876581', 'bflippen3g@blogger.com', 2100, 2);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Gusti', 'Rucklesse', null, '3756219312', 'grucklesse3h@accuweather.com', 2423, 44);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Holt', 'Patemore', '00461 Pierstorff Terrace', '7575180930', 'hpatemore3i@gizmodo.com', 1712, 35);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Neddie', 'Ebden', '6168 Green Drive', null, 'nebden3j@forbes.com', 2923, 16);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Sheelagh', 'Mackneis', null, '6562037517', 'smackneis3k@spiegel.de', 1612, 50);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Maureen', 'Carnilian', '1 Melvin Park', null, 'mcarnilian3l@fastcompany.com', 2113, 12);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Omero', 'Matiebe', null, null, 'omatiebe3m@godaddy.com', 1804, 49);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Dareen', 'Angelini', null, null, 'dangelini3n@smugmug.com', 2030, 10);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Kinnie', 'Jeffes', null, '5423934384', 'kjeffes3o@list-manage.com', 2135, 23);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Tommy', 'Acreman', null, '3925076209', 'tacreman3p@sakura.ne.jp', 2512, 5);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Bern', 'Dickerline', null, '2158420466', 'bdickerline3q@nih.gov', 2588, 6);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Charita', 'Nyles', null, null, 'cnyles3r@oracle.com', 2619, 6);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Othelia', 'Tinghill', null, '2755187190', 'otinghill3s@state.tx.us', 1804, 12);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Jenna', 'Jallin', '26965 Lighthouse Bay Parkway', '8149598983', 'jjallin3t@ovh.net', 2642, 25);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Kearney', 'Ashingden', null, '2888796211', 'kashingden3u@stanford.edu', 2375, 23);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Kearney', 'Twentyman', null, '9935013356', 'ktwentyman3v@behance.net', 1917, 34);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Kerry', 'Wyndham', null, '4653714095', 'kwyndham3w@ustream.tv', 2189, 36);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Marcelia', 'Rampley', null, '4223946352', 'mrampley3x@npr.org', 2963, 41);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Larisa', 'Featherstonhalgh', '2835 Hollow Ridge Parkway', '6743308053', null, 1655, 31);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Eziechiele', 'Aldham', null, '2422170761', 'ealdham3z@army.mil', 2922, 45);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Erick', 'Domican', null, '3674552754', 'edomican40@about.com', 1886, 48);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Esdras', 'Malpas', '717 Hoffman Court', null, 'emalpas41@imdb.com', 1939, 35);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Theo', 'Kinnon', '98 Hoffman Center', '8029497986', 'tkinnon42@amazon.co.jp', 2997, 40);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Enrichetta', 'Precious', null, null, 'eprecious43@php.net', 2245, 44);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Leslie', 'Bussen', null, '9042550991', 'lbussen44@ebay.co.uk', 2248, 16);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Marla', 'Mabbutt', '655 Graedel Plaza', '3097739650', 'mmabbutt45@wired.com', 2137, 22);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Hort', 'Gilliam', null, '7706081440', 'hgilliam46@bloglines.com', 2706, 20);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Carlota', 'Mascall', null, null, 'cmascall47@ameblo.jp', 2219, 23);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Lusa', 'Boal', null, '8875657615', 'lboal48@xing.com', 2584, 2);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Rosco', 'Drinkall', null, '9725500194', 'rdrinkall49@boston.com', 1678, 7);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Arlin', 'McOmish', null, null, 'amcomish4a@elegantthemes.com', 2937, 26);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Juline', 'Dionisetto', null, '5743034006', 'jdionisetto4b@newyorker.com', 2825, 17);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Kathleen', 'Musicka', null, null, 'kmusicka4c@auda.org.au', 1861, 18);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Chaddie', 'Petrello', '18669 Corben Avenue', '4179391013', 'cpetrello4d@elegantthemes.com', 1780, 19);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Les', 'MacIlurick', '6 Hanover Place', '7579395671', null, 2926, 37);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Sile', 'Lockitt', null, null, 'slockitt4f@yale.edu', 2497, 14);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Kerrin', 'Kendle', null, null, 'kkendle4g@icio.us', 2680, 50);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Wolfgang', 'Felmingham', null, null, 'wfelmingham4h@pagesperso-orange.fr', 2459, 37);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Clyde', 'Stacy', null, '3348835243', null, 2783, 31);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Rollie', 'Kinder', null, null, 'rkinder4j@netvibes.com', 2883, 34);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Nolana', 'Cloney', null, '4312893817', 'ncloney4k@delicious.com', 2018, 39);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Konstantin', 'Pennycord', '5388 Russell Drive', '9434027889', 'kpennycord4l@sitemeter.com', 2276, 40);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Kate', 'MacCambridge', null, '5296194793', 'kmaccambridge4m@google.es', 2157, 39);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Karol', 'Loweth', null, '3458087482', 'kloweth4n@wikimedia.org', 1607, 25);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Katina', 'Tibald', '119 Pine View Avenue', '6645040258', 'ktibald4o@cisco.com', 1890, 24);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Hermon', 'Finlaison', '7 Summit Place', '2192611871', 'hfinlaison4p@quantcast.com', 2312, 31);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Isahella', 'Swanborough', null, '9766844488', 'iswanborough4q@ox.ac.uk', 2307, 36);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Sonni', 'Heynen', '660 Mosinee Crossing', '7897373864', 'sheynen4r@fc2.com', 2733, 7);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Timothee', 'Pointing', null, '5463656906', 'tpointing4s@acquirethisname.com', 1660, 8);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Donnie', 'Monard', null, '7113274210', 'dmonard4t@hc360.com', 1673, 7);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Kinnie', 'McMickan', null, '4582928505', 'kmcmickan4u@alibaba.com', 1881, 26);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Tomaso', 'Hoggan', null, '5888849967', 'thoggan4v@usa.gov', 1874, 39);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Hardy', 'Ellerby', '734 Meadow Ridge Junction', '5535972880', 'hellerby4w@sfgate.com', 2268, 30);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Gertrude', 'Duny', null, '8322523261', 'gduny4x@clickbank.net', 2850, 49);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Branden', 'Rummings', null, '4213448762', 'brummings4y@fotki.com', 1786, 27);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Richard', 'Beeze', null, '6309289785', 'rbeeze4z@usa.gov', 2415, 46);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Franklin', 'Pardie', null, null, 'fpardie50@nsw.gov.au', 2331, 2);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Muffin', 'Debnam', '0390 Packers Lane', null, 'mdebnam51@google.cn', 2294, 43);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Hinda', 'Hourihan', null, '2588398052', 'hhourihan52@mlb.com', 1953, 11);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Modestine', 'Daldry', null, '2533712582', 'mdaldry53@baidu.com', 2591, 20);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Delbert', 'Otton', null, '6851210458', 'dotton54@ycombinator.com', 2839, 48);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Joeann', 'Checcuzzi', null, '5477898499', 'jcheccuzzi55@comsenz.com', 2258, 38);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Grannie', 'Stringfellow', null, '5226187324', 'gstringfellow56@webs.com', 1914, 47);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Carree', 'Jizhaki', null, '3268670772', 'cjizhaki57@sun.com', 2381, 14);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Morton', 'Trevaskus', null, '1632775591', 'mtrevaskus58@hugedomains.com', 2229, 19);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Maurizia', 'Harses', null, '4478992814', 'mharses59@dyndns.org', 2641, 41);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Una', 'Garritley', '1446 Talisman Circle', null, 'ugarritley5a@gov.uk', 2578, 12);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Jana', 'Cunio', null, null, 'jcunio5b@istockphoto.com', 2250, 33);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Cam', 'Bosma', null, '8139488267', 'cbosma5c@google.com', 1894, 18);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Michal', 'Nann', '734 Stone Corner Plaza', null, 'mnann5d@soup.io', 2199, 16);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Pia', 'Dorsey', null, '8644106329', 'pdorsey5e@hhs.gov', 1754, 7);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Ediva', 'Cayet', '07933 Pleasure Trail', '3155073405', 'ecayet5f@marriott.com', 1517, 8);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Bryn', 'Kerner', null, null, 'bkerner5g@bravesites.com', 2604, 47);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Margaret', 'Shord', null, null, 'mshord5h@naver.com', 2872, 17);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Alisa', 'Paulou', null, '1624604403', 'apaulou5i@xinhuanet.com', 1671, 37);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Glen', 'Benallack', null, '5617420380', 'gbenallack5j@networkadvertising.org', 2520, 20);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Lemar', 'Whitrod', null, '7082938387', 'lwhitrod5k@yellowpages.com', 2989, 35);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Pauline', 'Tailour', '1167 Messerschmidt Terrace', '2113046313', 'ptailour5l@prlog.org', 2821, 6);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Nap', 'Battson', null, '2805944265', 'nbattson5m@lycos.com', 2957, 19);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Averell', 'Duval', '5745 Ridgeway Plaza', '5581815295', 'aduval5n@surveymonkey.com', 2401, 7);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Shaw', 'Longea', null, '6152775483', 'slongea5o@fotki.com', 1934, 5);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Mariejeanne', 'Zute', '39931 Elmside Crossing', '9809275132', 'mzute5p@elegantthemes.com', 2551, 3);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Aldo', 'Gibbett', null, '4718783980', null, 2241, 17);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Ruddie', 'Hunnam', '73328 Arkansas Parkway', null, 'rhunnam5r@reverbnation.com', 2337, 32);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Tammy', 'Eles', null, '8101506248', 'teles5s@typepad.com', 2571, 44);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Tedie', 'Pincked', null, '2104102513', 'tpincked5t@pcworld.com', 2511, 36);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Nariko', 'Toller', '5013 Bowman Hill', '2812159223', null, 2438, 46);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Hubey', 'Stovold', null, '5476614723', 'hstovold5v@flickr.com', 2215, 10);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Mikael', 'Carley', null, '6398816608', 'mcarley5w@businessweek.com', 2782, 20);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Fairlie', 'McClean', null, null, 'fmcclean5x@chronoengine.com', 2736, 2);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Amye', 'Copley', '74747 Daystar Trail', '8942778191', 'acopley5y@indiatimes.com', 2108, 39);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Lin', 'Jenckes', null, '8749770121', 'ljenckes5z@unblog.fr', 1563, 39);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Janot', 'Turnpenny', null, '7006697718', 'jturnpenny60@google.com.br', 1779, 1);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Fern', 'Talton', null, '8969364065', 'ftalton61@time.com', 2730, 11);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Elena', 'Sheerin', null, '3798055055', 'esheerin62@prweb.com', 2287, 40);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Myranda', 'Boutell', null, '7601005890', 'mboutell63@timesonline.co.uk', 2737, 33);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Murry', 'Heavens', null, null, 'mheavens64@topsy.com', 2103, 36);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Eveline', 'Simkins', '41921 Mitchell Circle', null, 'esimkins65@facebook.com', 1648, 22);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Konstanze', 'Ells', '902 Homewood Road', null, 'kells66@opera.com', 2081, 15);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Fifi', 'Rackam', null, '4244496939', 'frackam67@i2i.jp', 1884, 43);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Reece', 'MacLaren', null, null, 'rmaclaren68@reverbnation.com', 2747, 41);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Loretta', 'Scogin', null, null, 'lscogin69@jiathis.com', 1606, 45);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Niccolo', 'Withrop', null, null, 'nwithrop6a@csmonitor.com', 1659, 16);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Ida', 'Stoving', null, null, 'istoving6b@craigslist.org', 1611, 47);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Betta', 'Husby', '5571 Milwaukee Drive', '9738775716', 'bhusby6c@phoca.cz', 2898, 45);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Kessia', 'Madill', null, '9302854174', null, 2822, 14);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Roobbie', 'Gogin', null, '4587334850', 'rgogin6e@alexa.com', 2120, 4);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Wally', 'Marrian', null, '5444987081', 'wmarrian6f@berkeley.edu', 2754, 38);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Marie-jeanne', 'Seyler', null, '2067484959', 'mseyler6g@soundcloud.com', 2975, 18);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('William', 'Keatley', null, '4871660640', 'wkeatley6h@addtoany.com', 2057, 50);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Anna-diane', 'Sonschein', null, '5032414673', 'asonschein6i@upenn.edu', 2632, 38);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Cory', 'Paute', '76942 Ridgeway Drive', '6694201878', 'cpaute6j@zdnet.com', 1545, 25);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Evin', 'Rothon', '090 Sunbrook Point', null, null, 2456, 7);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Ailis', 'Tumility', null, '2034314434', 'atumility6l@ucsd.edu', 2183, 26);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Edd', 'Cupper', null, '5812948826', 'ecupper6m@tamu.edu', 1977, 28);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Eden', 'Borland', null, null, 'eborland6n@sina.com.cn', 1668, 30);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Giacopo', 'Fripp', '58117 Ludington Road', '2852094843', 'gfripp6o@odnoklassniki.ru', 2908, 28);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Ann-marie', 'Charman', null, '4456484199', 'acharman6p@dot.gov', 2317, 18);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Hildagard', 'Latter', null, '7524424260', 'hlatter6q@upenn.edu', 2532, 8);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Tanya', 'Krier', null, null, 'tkrier6r@prlog.org', 1659, 40);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Muhammad', 'Fouracres', null, null, 'mfouracres6s@state.gov', 2158, 4);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Augustus', 'Haws', '85 Manley Place', '9209285605', 'ahaws6t@house.gov', 1711, 20);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Fergus', 'Egglestone', null, '9041638808', 'fegglestone6u@yelp.com', 2621, 7);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Sampson', 'Sibthorp', null, '6609065322', 'ssibthorp6v@reddit.com', 1787, 44);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Gregory', 'Jeffcoat', '163 Clarendon Plaza', '1273134134', 'gjeffcoat6w@dyndns.org', 2562, 25);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Jorgan', 'Jerzak', null, null, null, 1506, 35);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Leonerd', 'Tyres', '8 Bobwhite Street', '1407492789', null, 2688, 22);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Alfie', 'Franz', null, '5827323785', 'afranz6z@diigo.com', 1622, 24);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Dale', 'Fenny', null, '1225769208', 'dfenny70@census.gov', 2462, 21);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Bernadine', 'O''Sherrin', null, '4459606516', 'bosherrin71@apache.org', 1769, 46);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Nial', 'Darnbrook', '832 John Wall Center', '1876584103', null, 1832, 39);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Berne', 'Whewell', null, '1444995206', 'bwhewell73@huffingtonpost.com', 2773, 15);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Waylin', 'Deavall', null, '2912528651', 'wdeavall74@ucoz.ru', 2957, 36);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Rainer', 'Launder', null, '3763060805', 'rlaunder75@theglobeandmail.com', 2396, 7);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Ricard', 'Ing', '85219 Armistice Trail', null, 'ring76@last.fm', 2913, 40);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Kay', 'Codlin', null, '7652022031', 'kcodlin77@bravesites.com', 1624, 28);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Gretchen', 'Meynell', null, null, 'gmeynell78@cam.ac.uk', 2935, 8);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Harmony', 'Pridding', null, '3989660466', 'hpridding79@drupal.org', 2584, 18);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Verla', 'Screen', '8104 Ramsey Point', '6897130735', 'vscreen7a@tripod.com', 2968, 10);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Wallas', 'Grisard', '78 Packers Center', '9986500894', 'wgrisard7b@last.fm', 2978, 35);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Rafa', 'Feldheim', null, null, 'rfeldheim7c@nih.gov', 2295, 17);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Barbi', 'Bibb', '79 Coolidge Road', '3008964089', 'bbibb7d@wiley.com', 2134, 23);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Dita', 'McQuaide', null, '6647864849', 'dmcquaide7e@yellowbook.com', 2323, 29);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Adaline', 'Radbone', null, null, 'aradbone7f@unc.edu', 2652, 16);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Paula', 'Tubritt', '78 Summer Ridge Parkway', '4886733197', 'ptubritt7g@typepad.com', 1985, 11);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Tyrus', 'Wiggett', null, null, 'twiggett7h@unesco.org', 2777, 7);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Sidonnie', 'Valentinuzzi', '16293 Fulton Point', '7358886786', null, 1806, 24);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Valeda', 'Skehan', null, '6145771926', 'vskehan7j@reddit.com', 2940, 24);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Matthaeus', 'De Ruggiero', null, null, 'mderuggiero7k@cnbc.com', 2894, 2);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Jeannine', 'Dike', null, '5535085814', 'jdike7l@va.gov', 2605, 19);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Romy', 'Mendenhall', null, '9485505143', 'rmendenhall7m@cnn.com', 1905, 16);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Flss', 'Gurnett', null, '1569343913', null, 2044, 13);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Mendel', 'MacTrustram', '6 Burning Wood Road', '4514966320', 'mmactrustram7o@hugedomains.com', 1748, 8);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Caren', 'Pick', null, '3823930317', 'cpick7p@yellowpages.com', 2890, 47);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Englebert', 'Rothschild', null, '5199148173', 'erothschild7q@prnewswire.com', 2160, 40);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Gerta', 'Maeer', '45 Muir Way', null, 'gmaeer7r@opera.com', 1916, 36);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Ursula', 'Treat', '7 Dexter Way', null, 'utreat7s@seattletimes.com', 2608, 27);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Bordy', 'Rickaert', null, '6319927937', 'brickaert7t@unc.edu', 1621, 5);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Adoree', 'Legges', null, '5903176148', 'alegges7u@samsung.com', 2496, 17);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Glynn', 'Jannex', null, '8194457076', 'gjannex7v@nytimes.com', 1708, 11);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Sawyere', 'Postin', '973 School Trail', '2646845289', 'spostin7w@buzzfeed.com', 2598, 2);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Maria', 'Sorley', '8454 Sachs Junction', '1367244891', 'msorley7x@wiley.com', 2041, 42);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Iris', 'Salandino', null, '2127972786', 'isalandino7y@yale.edu', 1631, 9);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Erma', 'Bahia', null, '3711330305', 'ebahia7z@wordpress.com', 1821, 29);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Ely', 'Messer', null, null, null, 2670, 2);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Lauritz', 'Bohden', null, '8057375079', 'lbohden81@histats.com', 2846, 37);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Gail', 'Roffe', null, '1712080558', 'groffe82@ning.com', 1650, 48);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Roxine', 'Seymark', null, null, 'rseymark83@ifeng.com', 1686, 24);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Silvie', 'Pile', null, '5603281757', 'spile84@umich.edu', 1795, 45);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Jehu', 'Gerraty', null, '7588906033', 'jgerraty85@unicef.org', 1953, 45);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Adolf', 'Tilberry', null, '7657706996', 'atilberry86@dion.ne.jp', 2753, 9);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Fulvia', 'Rubenovic', null, '7565223059', 'frubenovic87@nationalgeographic.com', 1572, 19);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Nelie', 'Keers', null, '9736526573', 'nkeers88@buzzfeed.com', 2875, 38);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Cele', 'Fake', '3 Lukken Plaza', '7843161168', 'cfake89@t-online.de', 2169, 18);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Barbra', 'Boarer', null, '8167379669', 'bboarer8a@smh.com.au', 1934, 6);
insert into players (first_name, last_name, address, phone_number, email, rank, club_id) values ('Lynsey', 'Seares', null, '4209475110', 'lseares8b@bluehost.com', 2497, 36);
